version: 0.0
os: linux
files:
  - source: Styleboso.war
    destination: /usr/local/tomcat/webapps
hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: root