version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven
      - yum install -y maven
  pre_build:
    commands:
      - echo Build started on `date`
      - cd /Styleboso && mvn clean install
  build:
    commands:
      - echo Packaging application
      - mv target/controller-1.0.0-BUILD-SNAPSHOT.war Styleboso.war
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - Styleboso.war
    - appspec.yml
    - scripts/*
